### ISSUE TITLE
Using 1filellm open large git repository and generate prompts for LLMs

### ISSUE THREAD

**Issue by LZING** [jimmc414/1filellm#15] opened 2024-06-25 07:58 UTC
Hi, jimmc414. Thank you for a very nice application.

I'm running into a problem right now when dealing with large code repositories. When I'm dealing with small code repositories, 1filellm works great. But when I'm dealing with large repositories, I have a token overflow problem when interacting with LLM.

So how should we deal with large code repositories? Sending only part of the source code will affect the context. Now it seems that only Gemini 1.5pro can handle about 200m tokens, which is the upper limit.

Do you have any good suggestions?

**Comment by jimmc414** [comment] 2024-06-26 11:36
Hi, thank you!   do you have an example repo I can use for testing?

**Comment by LZING** [comment] 2024-06-27 05:59
> Hi, LZING thank you! do you have an example repo URL I can use for testing?

Thx jimmc414, we are using the framework of this project. This project is quite large, and all ts and js add up to nearly 400M tokens. I think it should be divided into modules or folders to process.
The repo address is: https://github.com/backstage/backstage/tree/master

**Comment by jimmc414** [comment] 2024-07-08 22:25
I was able to reproduce the issue.  However, it appears that the issue is that Github's API is timing out, not the python code.  If you download the entire repo locally then process the local folder, all 12 million tokens will process.  The fix for this would be to add pagination to the download, but that would come at a performance cost for normal size repos.  Given that the largest context window at present is 2 million tokens and this repo is a total of 12,000,000 tokens, the best solution would be to download repos over 2 million tokens locally and the will process without error.  Let me know if this doesn't work for you.

**Closed by jimmc414** 2024-07-08 22:25 UTC
